---
- name: Provision VM
  hosts: all
  become: true
  become_method: sudo
  remote_user: tm_admin
  vars:
    gh_runner_config_token: ATVEQVDP4WUZ2JLQDKS2SQDFKE5NK
    gh_runner_remove_token: ATVEQVACDW7ATVQIB55BLHDFKELUQ
  tasks:
    - import_tasks: ./roles/docker/tasks/tasks.yml
    - import_tasks: ./roles/github/tasks/task.yml
