- name: install utility packages
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes

  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common


- name: GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker repository to apt
  apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present


- name: install docker
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose

- name: append tm_admin to group
  user:
    name: tm_admin
    groups: docker
    append: true

- name: create script to delete containers and images
  copy:
    src: ../files/delete_container.sh
    dest: /opt/delete_container.sh
    owner: tm_admin
    mode: 0755
  become: true
