name: Build time_manager

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    
    - name: delete containers
      continue-on-error: true
      run: /opt/delete_container.sh

    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d --build
